server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/projectDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5430/projectDB
    user: postgres
    password: postgres
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    show-sql: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE